server:
  port: 8080
spring:
  application:
    name: rabbitmq
  rabbitmq:
    host: localhost
    virtual-host: /
    port: 5672
    publisher-confirm-type: correlated
    publisher-returns: true

  aop:
    proxy-target-class: false